# [Info]
site_name: Sihan A # 左上角标题
site_url: https://sihan-a.github.io/wiki
site_author: Sihan A
site_description: Wiki Page

nav:
  - 🛠 Tools:
    - index: tools/index.md
    - 🖥 Software Engineering:
      - index: tools/se/index.md
      - Hydra: tools/se/hydra.md
      - Git & GitHub: tools/se/git.md
    - 💡 Compute:
      - Google Colab: tools/compute/google-colab.md
    - 🏝 Resource:
      - 🌅 Environment: tools/resource/environment.md
      - 🐳 Docker: tools/resource/docker.md
      - 🎻 Kubernetes: tools/resource/kubernetes.md
    - 🛢 Data:
      - index: tools/data/index.md
    - 🤔 Other:
      - index: tools/other/index.md
      - MacOS: tools/other/macos.md
      - Markdown: tools/other/markdown.md
      - VS Code: tools/other/vscode.md

  - 📊 Data Science:
    - index:          ds/index.md
    - ⭐️ Machine Learning:
      - Supervised:   ds/ml/supervised.md
      - Unsupervised: ds/ml/unsupervised.md
      - Ensemble:     ds/ml/ensemble.md
      - Trees:        ds/ml/trees.md
      - Metrics:      ds/ml/metrics.md
      - Concepts:     ds/ml/concepts.md
    - 📷 Computer Vision:
      - index:        ds/cv/index.md
      - Preprocess:   ds/cv/preprocess.md
  - 📝 Learning:
    - index:       learn/index.md
    - 🍣 日本語:
      - index:     learn/japanese/index.md
      - 🍢 N2红宝书:
        - index:   learn/japanese/n2-vocabulary/index.md
        - 第01单元: learn/japanese/n2-vocabulary/第01单元.md
        - 第02单元: learn/japanese/n2-vocabulary/第02单元.md
        - 第03单元: learn/japanese/n2-vocabulary/第03单元.md
        - 第04单元: learn/japanese/n2-vocabulary/第04单元.md
        - 第05单元: learn/japanese/n2-vocabulary/第05单元.md
        - 第06单元: learn/japanese/n2-vocabulary/第06单元.md
        - 第07单元: learn/japanese/n2-vocabulary/第07单元.md
        - 第08单元: learn/japanese/n2-vocabulary/第08单元.md
        - 第09单元: learn/japanese/n2-vocabulary/第09单元.md
        - 第10单元: learn/japanese/n2-vocabulary/第10单元.md
        - 第11单元: learn/japanese/n2-vocabulary/第11单元.md
        - 第12单元: learn/japanese/n2-vocabulary/第12单元.md
        - 第13单元: learn/japanese/n2-vocabulary/第13单元.md
        - 第14单元: learn/japanese/n2-vocabulary/第14单元.md
        - 第15单元: learn/japanese/n2-vocabulary/第15单元.md
        - 第16单元: learn/japanese/n2-vocabulary/第16单元.md
        - 第17单元: learn/japanese/n2-vocabulary/第17单元.md
        - 第18单元: learn/japanese/n2-vocabulary/第18单元.md
        - 第19单元: learn/japanese/n2-vocabulary/第19单元.md
        - 第20单元: learn/japanese/n2-vocabulary/第20单元.md
      - 日语动词变形: learn/japanese/日语动词变形.md

     
# [UI]
## [top]
theme:
  name: material
  font: 
    text: Work Sans
  palette: 
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: 切换至夜间模式
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Mode
  features:
    - navigation.tabs       # 使用Tab来进行分类
    - navigation.top        # 返回顶部的按钮 在上滑时出现
    - navigation.indexes    # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand     # 打开Tab时左侧目录全部展开
    - search.suggest        # 搜索输入一些字母时推荐补全整个单词
    - search.highlight      # 搜索出的文章关键词加入高亮
  language: en
  icon:
    repo: fontawesome/brands/github

edit_uri: edit/main/docs    # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Sihan-A/wiki # 右上角点击跳转的链接
repo_name: Sihan-A/wiki          # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 Sihan A

## [bottom-right corner]
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sihan-A
      name: GitHub | Sihan A
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sihan-a/
      name: LinkedIn | Sihan A


# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex support
      generic: true
  - attr_list            # image
  - md_in_html           # image
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols