# [Info]
site_name: Sihan A # 左上角标题
site_url: https://sihan-a.github.io/wiki
site_author: Sihan A
site_description: Wiki Page

nav:
  - 🔧 Tools:
    - index: tools/index.md
    - 💻 Software Engineering:
      - index: tools/se/index.md
      - Python: tools/se/python.md
      - Configuration: tools/se/config.md
      - Linux: tools/se/linux.md
      - Git & GitHub: tools/se/git.md
    - 🎨 Data Science:
      - index: tools/ds/index.md
      - DS Libraries: tools/ds/ds_framework.md
      - Experiment: tools/ds/experiment.md
      - Visualization: tools/ds/viz.md
      - AutoML: tools/ds/automl.md
      - Time Series: tools/ds/time_series.md
      - Explainble AI: tools/ds/explainable.md
      - Jupyter: tools/ds/jupyter.md
    - 📦 Deep Learning:
      - index: tools/dl/index.md
      - PyTorch: tools/dl/torch.md
      - PyTorch Lightning: tools/dl/lightning.md
      - TensorFlow & Keras: tools/dl/tf.md
      - fast.ai: tools/dl/fastai.md
      - ONNX: tools/dl/onnx.md
    - 📸 Computer Vision:
      - index: tools/cv/index.md
      - Image Classification: tools/cv/classification.md
      - Object Detection: tools/cv/detection.md
      - Anomaly Detection: tools/cv/anomaly.md
    - 📓 NLP:
      - index: tools/nlp/index.md
      - 🤗 Hugging Face: tools/nlp/huggingface.md
    - 💡 Compute:
      - index: tools/compute/index.md
      - Google Colab: tools/compute/google-colab.md
    - 🪐 Resource Management:
      - index: tools/resource/index.md
      - 🌅 Environment: tools/resource/environment.md
      - 🐳 Docker: tools/resource/docker.md
      - 🧷 Kubernetes: tools/resource/kubernetes.md
    - 🔗 MLOps:
      - index: tools/mlops/index.md
      - Container for ML: tools/mlops/container_ml.md
      - Kubeflow: tools/mlops/kubeflow.md
    - 🔄 CI/CD:
      - index: tools/ci/index.md
      - Jenkins: tools/ci/jenkins.md
      - GitHub Actions: tools/ci/github_actions.md
      - CircleCI: tools/ci/circleci.md
    - 🎵 Data:
      - index: tools/data/index.md
      - Analysis: tools/data/analysis.md
      - EDA: tools/data/eda.md
      - DVC: tools/data/dvc.md
      - Annotations: tools/data/annotation.md
      - Imbalanced Data: tools/data/imbalance.md
      - Kafka: tools/data/kafka.md
      - Utilities: tools/data/utils.md
    - 🌊 Cloud:
      - index: tools/cloud/index.md
      - AWS: tools/cloud/aws.md
    - 🚎 Deployment:
      - index: tools/deploy/index.md
      - Backend: tools/deploy/backend.md
      - Frontend: tools/deploy/frontend.md
      - Heroku: tools/deploy/heroku.md
    - 🛕 Project Management:
      - index: tools/project/index.md
      - Jira: tools/project/jira.md
    - 🤔 Other:
      - index: tools/other/index.md
      - MacOS: tools/other/macos.md
      - Windows: tools/other/win.md
      - VS Code: tools/other/vscode.md
      - Markdown: tools/other/markdown.md
      - LaTex: tools/other/latex.md
      

  - 📊 Data Science:
    - index:          ds/index.md
    - ⭐️ Machine Learning:
      - index: ds/ml/index.md
      - Supervised:   ds/ml/supervised.md
      - Unsupervised: ds/ml/unsupervised.md
      - Ensemble:     ds/ml/ensemble.md
      - Trees:        ds/ml/trees.md
      - Metrics:      ds/ml/metrics.md
      - Concepts:     ds/ml/concepts.md
    - Deep Learning:
      - index: ds/dl/index.md
      - CNN: ds/dl/cnn.md
      - RNN: ds/dl/rnn.md
      - Transformer: ds/dl/transformer.md
      - Diffusion: ds/dl/diffusion.md
    - 📷 Computer Vision:
      - index:        ds/cv/index.md
      - Preprocess:   ds/cv/preprocess.md
  - 📝 Learning:
    - index: learn/index.md
    
    - 🥮 Deep Learning:
      - index: learn/dl/index.md
      - FSDL 2022:
        - index: learn/dl/fsdl2022/index.md
        - 01 Introduction: learn/dl/fsdl2022/01-intro.md
      - Lee 2021:
        - index: learn/dl/lee2021/index.md
      - Lee 2022:
        - index: learn/dl/lee2022/index.md
        - Rules: learn/dl/lee2022/01-rules.md
        - Labs:
          - index: learn/dl/lee2022/labs/index.md
    - 🚅 Machine Learning:
      - index: learn/ml/index.md
      - CS329S Machine Learning Systems Design:
        - index: learn/ml/cs329s/index.md
    - 🍣 日本語:
      - index: learn/japanese/index.md
      - 🍢 N2红宝书:
        - index:   learn/japanese/n2-vocabulary/index.md
        - 第01单元: learn/japanese/n2-vocabulary/第01单元.md
        - 第02单元: learn/japanese/n2-vocabulary/第02单元.md
        - 第03单元: learn/japanese/n2-vocabulary/第03单元.md
        - 第04单元: learn/japanese/n2-vocabulary/第04单元.md
        - 第05单元: learn/japanese/n2-vocabulary/第05单元.md
        - 第06单元: learn/japanese/n2-vocabulary/第06单元.md
        - 第07单元: learn/japanese/n2-vocabulary/第07单元.md
        - 第08单元: learn/japanese/n2-vocabulary/第08单元.md
        - 第09单元: learn/japanese/n2-vocabulary/第09单元.md
        - 第10单元: learn/japanese/n2-vocabulary/第10单元.md
        - 第11单元: learn/japanese/n2-vocabulary/第11单元.md
        - 第12单元: learn/japanese/n2-vocabulary/第12单元.md
        - 第13单元: learn/japanese/n2-vocabulary/第13单元.md
        - 第14单元: learn/japanese/n2-vocabulary/第14单元.md
        - 第15单元: learn/japanese/n2-vocabulary/第15单元.md
        - 第16单元: learn/japanese/n2-vocabulary/第16单元.md
        - 第17单元: learn/japanese/n2-vocabulary/第17单元.md
        - 第18单元: learn/japanese/n2-vocabulary/第18单元.md
        - 第19单元: learn/japanese/n2-vocabulary/第19单元.md
        - 第20单元: learn/japanese/n2-vocabulary/第20单元.md
      - 日语动词变形: learn/japanese/日语动词变形.md
    - 🌏 AWS:
      - index: learn/aws/index.md
      - Cloud Practitioner: learn/aws/ccp.md
  - 📚 Projects:
    - index: projects/index.md
    - Wiki: projects/wiki.md
# UI
# top
theme:
  name: material
  font: 
    text: Work Sans
  palette: 
    - scheme: default
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-night
        name: 切换至夜间模式
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Mode
  features:
    - navigation.tabs       # 使用Tab来进行分类
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.top        # 返回顶部的按钮 在上滑时出现
    - navigation.indexes    # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand     # 打开Tab时左侧目录全部展开
    - search.suggest        # 搜索输入一些字母时推荐补全整个单词
    - search.highlight      # 搜索出的文章关键词加入高亮
  language: en
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs    # 编辑按钮跳转的链接
# top-right corner
repo_url: https://github.com/Sihan-A/wiki # 右上角点击跳转的链接
repo_name: Sihan-A/wiki # 右上角的名字
# bottom-left corner
copyright: Copyright &copy; 2022 Sihan A
# bottom-right corner
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sihan-A
      name: GitHub | Sihan A
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sihan-a/
      name: LinkedIn | Sihan A
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/sihana
      name: Kaggle | Sihan A
    - icon: fontawesome/brands/medium
      link: https://medium.com/@sihan-a
      name: Medium | Sihan A
# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex support
      generic: true
  - attr_list            # image
  - md_in_html           # image
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols